# Generated by Django 4.2.3 on 2023-07-09 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaModelo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActulizacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notas',
                'ordering': ['fechaCreacion'],
            },
        ),
    ]
